image:
  repository: velero/velero
  tag: v1.3.1
  digest: sha256:0c74f1d552ef25a4227e582f4c0e6b3db3402abe196595ee9442ceeb43b99696
  pullPolicy: IfNotPresent

initContainers: 
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  enabled: true
  scrapeInterval: 30s

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    enabled: false
    additionalLabels: {}

installCRDs: true

configuration:
  provider: gcp
  backupStorageLocation:
    name: default
    bucket: velero-hhesham 

  volumeSnapshotLocation:
    name: default

  logLevel: info
  logFormat:

rbac:
  create: true
  clusterAdministrator: true

serviceAccount:
  server:
    create: true
    name:
    annotations:

credentials:
  useSecret: true
  existingSecret: credentials-velero

backupsEnabled: true
snapshotsEnabled: true

deployRestic: false
